---

- name: Remove Data Services associated with the environment
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:

############# Environment Discovery & Validation #############

    # Find details about the environment
    - name: Discover and Validate CDP environment details
      tags:
        - always
      block:
        - name: Set environment name from either pre-existing environment or Terraform outputs
          ansible.builtin.set_fact:
            cdp_environment_name: "{{ cdp_env if cdp_env is defined else lookup('cloud.terraform.tf_output', 'cdp_environment_name', project_path=[playbook_dir,'tf-cdp-env'] | path_join) }}"

        - name: Retrieve details of the CDP environment
          cloudera.cloud.env_info:
            name: "{{ cdp_environment_name }}"
          register: __cdp_environment_info

        - name: Verify that environment is in running state
          ansible.builtin.assert:
            that:
              - __cdp_environment_info.environments | length == 1
              - __cdp_environment_info.environments[0].status == 'AVAILABLE'
            fail_msg: "Environment '{{ cdp_environment_name }}' not found or not in Available state"

        # Extract details about the environment
        - name: Find details about __cdp_environments_to_delete
          ansible.builtin.set_fact:
            __env_details: "{{ env_details }}"
          vars:
            network_details: "{{ (__cdp_environment_info.environments |  selectattr('environmentName', 'contains', cdp_environment_name)|first).network | default([]) }}"
            cloud_platform: "{{ (__cdp_environment_info.environments |  selectattr('environmentName', 'contains', cdp_environment_name)|first).cloudPlatform }}"
            env_details: 
              env_name: "{{ (__cdp_environment_info.environments |  selectattr('environmentName', 'contains', cdp_environment_name)|first).environmentName }}"
              crn: "{{ (__cdp_environment_info.environments |  selectattr('environmentName', 'contains', cdp_environment_name)|first).crn }}"
              status: "{{ (__cdp_environment_info.environments |  selectattr('environmentName', 'contains', cdp_environment_name)|first).status }}"
              cloud_platform: "{{ cloud_platform }}"
              region: "{{ (__cdp_environment_info.environments |  selectattr('environmentName', 'contains', cdp_environment_name)|first).region }}"
              credential_name: "{{ (__cdp_environment_info.environments |  selectattr('environmentName', 'contains', cdp_environment_name)|first).credentialName| default(omit)}}"
              # network id key is cloud platform dependent
              network_id: "{{ network_details[cloud_platform | lower] | default(None) | community.general.json_query('networkId||vpcId||networkName') or omit }}"
              subnets: "{{ network_details | community.general.json_query('subnetIds') or omit }}"

############# CML #############

    - name: Execute CML teardown
      tags:
        - cml
      block:
        - name: Retrieve details of CML Workspaces
          cloudera.cloud.ml_info:
            environment: "{{ __env_details.env_name }}"
          register: __cml_info
        
        - name: Disable CML workspaces
          cloudera.cloud.ml:
            name: "{{ __cml_item.instanceName }}"
            environment: "{{ __env_details.env_name }}"
            state: absent
            force: "{{ 'no' if __cml_item.instanceStatus == 'installation:finished' else 'yes' }}"
            wait: yes
          loop_control:
            loop_var: __cml_item
            label: "{{ __cml_item.instanceName }}"
          loop: "{{ __cml_info.workspaces }}"
          async: 3600 # 1 hour timeout
          poll: 0
          register: __cml_async         

############# CML - Wait #############
    - name: Monitor the delete of the CML workspaces
      when:
        - __cml_async is defined
        - __cml_async.results is defined
        - __cml_async.results | length > 0
      ansible.builtin.async_status:
        jid: "{{ __teardown.ansible_job_id }}"
      loop_control:
        loop_var: __teardown
        label: "{{ __teardown.__cml_item.instanceName | default('Unknown') }}"
      loop: "{{ __cml_async.results }}"
      register: __teardown_async
      until: __teardown_async.finished
      retries: 120
      delay: 30
      tags:
        - cml
